<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SendEmailWithoutLoginWithInvalidCredentialsinFromField" failures="1" tests="1" time="1.062" errors="0">
  <properties/>
  <testcase name="test_SendEmailWithoutLoginWithInvalidCredentialsinFromField" time="1.062" classname="com.sharethis.QAAutomation.OAuth.Email.SendEmailWithoutLoginWithInvalidCredentialsinFromField">
    <failure type="java.lang.RuntimeException" message="Could not contact Selenium Server; have you started it on &apos;localhost:4444&apos; ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect">
      <![CDATA[java.lang.RuntimeException: Could not contact Selenium Server; have you started it on 'localhost:4444' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect
	at com.thoughtworks.selenium.DefaultSelenium.start(DefaultSelenium.java:86)
	at com.sharethis.QAAutomation.commonlib.STLaunchBrowser.stLaunch(STLaunchBrowser.java:39)
	at com.sharethis.QAAutomation.OAuth.Email.SendEmailWithoutLoginWithInvalidCredentialsinFromField.test_SendEmailWithoutLoginWithInvalidCredentialsinFromField(SendEmailWithoutLoginWithInvalidCredentialsinFromField.java:28)
... Removed 22 stack frames]]>
    </failure>
  </testcase>
</testsuite>
